/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsModuleSlugIndexRouteImport } from './routes/skills.$moduleSlug.index'
import { Route as CoursesModuleSlugIndexRouteImport } from './routes/courses.$moduleSlug.index'
import { Route as SkillsModuleSlugLessonSlugRouteImport } from './routes/skills.$moduleSlug.$lessonSlug'
import { Route as CoursesModuleSlugLessonSlugRouteImport } from './routes/courses.$moduleSlug.$lessonSlug'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsModuleSlugIndexRoute = SkillsModuleSlugIndexRouteImport.update({
  id: '/$moduleSlug/',
  path: '/$moduleSlug/',
  getParentRoute: () => SkillsRoute,
} as any)
const CoursesModuleSlugIndexRoute = CoursesModuleSlugIndexRouteImport.update({
  id: '/$moduleSlug/',
  path: '/$moduleSlug/',
  getParentRoute: () => CoursesRoute,
} as any)
const SkillsModuleSlugLessonSlugRoute =
  SkillsModuleSlugLessonSlugRouteImport.update({
    id: '/$moduleSlug/$lessonSlug',
    path: '/$moduleSlug/$lessonSlug',
    getParentRoute: () => SkillsRoute,
  } as any)
const CoursesModuleSlugLessonSlugRoute =
  CoursesModuleSlugLessonSlugRouteImport.update({
    id: '/$moduleSlug/$lessonSlug',
    path: '/$moduleSlug/$lessonSlug',
    getParentRoute: () => CoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRouteWithChildren
  '/skills': typeof SkillsRouteWithChildren
  '/courses/$moduleSlug/$lessonSlug': typeof CoursesModuleSlugLessonSlugRoute
  '/skills/$moduleSlug/$lessonSlug': typeof SkillsModuleSlugLessonSlugRoute
  '/courses/$moduleSlug/': typeof CoursesModuleSlugIndexRoute
  '/skills/$moduleSlug/': typeof SkillsModuleSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRouteWithChildren
  '/skills': typeof SkillsRouteWithChildren
  '/courses/$moduleSlug/$lessonSlug': typeof CoursesModuleSlugLessonSlugRoute
  '/skills/$moduleSlug/$lessonSlug': typeof SkillsModuleSlugLessonSlugRoute
  '/courses/$moduleSlug': typeof CoursesModuleSlugIndexRoute
  '/skills/$moduleSlug': typeof SkillsModuleSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRouteWithChildren
  '/skills': typeof SkillsRouteWithChildren
  '/courses/$moduleSlug/$lessonSlug': typeof CoursesModuleSlugLessonSlugRoute
  '/skills/$moduleSlug/$lessonSlug': typeof SkillsModuleSlugLessonSlugRoute
  '/courses/$moduleSlug/': typeof CoursesModuleSlugIndexRoute
  '/skills/$moduleSlug/': typeof SkillsModuleSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/courses'
    | '/skills'
    | '/courses/$moduleSlug/$lessonSlug'
    | '/skills/$moduleSlug/$lessonSlug'
    | '/courses/$moduleSlug/'
    | '/skills/$moduleSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/courses'
    | '/skills'
    | '/courses/$moduleSlug/$lessonSlug'
    | '/skills/$moduleSlug/$lessonSlug'
    | '/courses/$moduleSlug'
    | '/skills/$moduleSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/courses'
    | '/skills'
    | '/courses/$moduleSlug/$lessonSlug'
    | '/skills/$moduleSlug/$lessonSlug'
    | '/courses/$moduleSlug/'
    | '/skills/$moduleSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  SkillsRoute: typeof SkillsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$moduleSlug/': {
      id: '/skills/$moduleSlug/'
      path: '/$moduleSlug'
      fullPath: '/skills/$moduleSlug/'
      preLoaderRoute: typeof SkillsModuleSlugIndexRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/courses/$moduleSlug/': {
      id: '/courses/$moduleSlug/'
      path: '/$moduleSlug'
      fullPath: '/courses/$moduleSlug/'
      preLoaderRoute: typeof CoursesModuleSlugIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/skills/$moduleSlug/$lessonSlug': {
      id: '/skills/$moduleSlug/$lessonSlug'
      path: '/$moduleSlug/$lessonSlug'
      fullPath: '/skills/$moduleSlug/$lessonSlug'
      preLoaderRoute: typeof SkillsModuleSlugLessonSlugRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/courses/$moduleSlug/$lessonSlug': {
      id: '/courses/$moduleSlug/$lessonSlug'
      path: '/$moduleSlug/$lessonSlug'
      fullPath: '/courses/$moduleSlug/$lessonSlug'
      preLoaderRoute: typeof CoursesModuleSlugLessonSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesModuleSlugLessonSlugRoute: typeof CoursesModuleSlugLessonSlugRoute
  CoursesModuleSlugIndexRoute: typeof CoursesModuleSlugIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesModuleSlugLessonSlugRoute: CoursesModuleSlugLessonSlugRoute,
  CoursesModuleSlugIndexRoute: CoursesModuleSlugIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface SkillsRouteChildren {
  SkillsModuleSlugLessonSlugRoute: typeof SkillsModuleSlugLessonSlugRoute
  SkillsModuleSlugIndexRoute: typeof SkillsModuleSlugIndexRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsModuleSlugLessonSlugRoute: SkillsModuleSlugLessonSlugRoute,
  SkillsModuleSlugIndexRoute: SkillsModuleSlugIndexRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoursesRoute: CoursesRouteWithChildren,
  SkillsRoute: SkillsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
